### ISSUE TITLE
Can't make a 2nd filtering function work

### ISSUE THREAD

**Issue by mcohen113** [mcohen113/Project2#2]
Trying to parse data via a 2nd key from API. Won't work.  Tried:
1) adding and existing subfunction (searchYears) within the parent function (holidayFunction) and changing parameters, then making corresponding changes to call function afterwards and in form of EJS page--> pages stays alive but data won't come through for either field--> pages says "enter a year'
2) tried setting up a new parent function in  another model page and putting the function in there, adding necessary lines to server.js-- this just makes the whole thing break from terminal
[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
/Users/Mike/code/wdi/homework/Project2/model/search.js:52
});
 ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Mike/code/wdi/homework/Project2/server.js:7:21)
    at Module._compile (module.js:556:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mcohen113** [comment]
@gittheking 
@jasonseminara 
@trevorpreston 
@rapala61
@irwintsay
